### ISSUE TITLE
Choose fields to exclude from scrape

### ISSUE THREAD

**Issue by stodpod** [tugkan/realtor-scraper#2]
Hi, awesome scraper! One feature that would be great would to be able to *exclude* fields from the scrape in the Apify input. 

Without that, I wind up with a file that's too big to manipulate locally, even with Anaconda.

**Comment by tugkan** [comment]
Hey @stodpod !

Thank you very much for using the scraper. On the dataset URL, you can filter it out by Apify's output URL. Example;

`https://api.apify.com/v2/datasets/XXXX/items?clean=true&format=html&fields=id,title,url,image`

However, if that is not enough for you, we can integrate an option called `customMapFunction` like our other actors so that you can manually select which fields you'd like to retrieve.

Best.

**Comment by stodpod** [comment]
Thanks for getting back to me @tugkan! 

I tried using the output URL as you suggested, and it works except that almost all fields are nested under `history` in the `sold` transactions. So if I put in `https://api.apify.com/v2/datasets/XXXX/items?clean=true&format=html&fields=history`, then I still get over 2,000 fields returned. 

Is there a way to encode the URL to find the first n items from a JSON list? For example, the first 3 `history` results for each sold property? That might do it.

Otherwise, the `customMapFunction` sounds like it would be great! Would it allow me to limit the results in nested JSON?

Thanks!

**Comment by tugkan** [comment]
Hey @stodpod !

The `customMapFunction` only allows you to map each of the rows in the dataset. So you can retrieve fewer data from a big dataset. However, filtering is not possible at the current moment, unfortunately. You need to get the data filtering over a 3rd party tool like Excel or JSON parser. 

Do you want us to integrate the `customMapFunction` still?
